development:
  dialect: postgres
  database: vigil-go
  user: postgres
  password:
  host: localhost
  pool: 5
  port: 5433

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5433/myapp_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5433/myapp_production"}}
